resources:
- name: auto-renderer
  type: git
  icon: github-circle
  source:
    uri: https://github.com/kc1r74p/autorender.git

jobs:
- name: list_ingress
  plan:
  - in_parallel:  
     - get: auto-renderer
  - task: mount_ingress
    privileged: true
    input_mapping: {renderer: auto-renderer}
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sh
        args:
        - -exc
        - |
          set +x
          apk add pv 2>&1 >/dev/null 
          apk add cifs-utils 2>&1 >/dev/null
          apk add --update nodejs npm 2>&1 >/dev/null
          #apk add ffmpeg 2>&1 >/dev/null 
          mkdir /mnt/ingress
          mount -t cifs ((nas_adr)) /mnt/ingress -o vers=3.0,username=((nas_adm)),password=((nas_pw)),dir_mode=0777,file_mode=0777,serverino
          ls -altrh
          cd /mnt/ingress
          ls -altrh
          #cd -
          #echo
          #echo
          #echo "Get part"
          #pv /mnt/ingress/GH010057.MP4 > ./GH010057.MP4
          #echo
          #ls -altrh
          #echo "Extract frame"
          #ffmpeg -i /mnt/ingress/GH010057.MP4 -s 2704x1520 -vframes 1 -f image2 frame.png
          #pv ./frame.png > /mnt/ingress/frame.png
          #tiv -w 80 -256 ./frame.png 
          npm -v
          node -v
          echo "done!"
