resources:
- name: auto-renderer
  type: git
  icon: github-circle
  source:
    uri: https://github.com/kc1r74p/autorender.git

- name: my-pipelines
  type: git
  icon: wrench
  source:
    uri: https://github.com/kc1r74p/my-pipelines.git

jobs:
- name: list_ingress
  plan:
  - in_parallel:  
     - get: auto-renderer
     - get: my-pipelines
  - task: mount_ingress
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu} 
      inputs:
        - name: auto-renderer
        - name: my-pipelines
      run:
        path: sh
        args:
        - -exc
        - |          
          apk add bash 2>&1 >/dev/null
          set +x
          export nas_adr=((nas_adr))
          export nas_adm=((nas_adm))
          export nas_pw=((nas_pw))
          cd my-pipelines/scripts/
          bash run_render.sh
