resources:
- name: auto-renderer
  type: git
  icon: github-circle
  source:
    uri: https://github.com/kc1r74p/autorender.git

jobs:
- name: list_ingress
  plan:
  - in_parallel:  
     - get: auto-renderer
  - task: mount_ingress
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu} 
      inputs:
        - name: auto-renderer
      run:
        path: sh
        args:
        - -exc
        - |
          set +x
          apk add pv 2>&1 >/dev/null 
          apk add cifs-utils 2>&1 >/dev/null
          apk add --update nodejs npm 2>&1 >/dev/null
          #apk add ffmpeg 2>&1 >/dev/null 
          mkdir /mnt/ingress
          mount -t cifs ((nas_adr)) /mnt/ingress -o vers=3.0,username=((nas_adm)),password=((nas_pw)),dir_mode=0777,file_mode=0777,serverino
          cd auto-renderer
          echo "Installing render deps..."
          npm i 2>&1 >/dev/null 
          echo "Building app..."
          npm run build
          cd dist
          mkdir in
          mkdir out
          mkdir final
          cd in
          echo "Copying ingress into container input..."
          pv /mnt/ingress/ingress/* > ./*
          cd ..
          cd ..
          echo "Running auto render..."
          npm start
          echo      
          echo "-------------------------"
          cd dist
          cd final
          echo "Retriving container output to share..."
          pv ./* > /mnt/ingress/
          echo      
          echo      
          echo "-------------------------"
          echo      
          echo "done!"
          echo      
          echo      
