jobs:
- name: job-hello-world
  public: true
  plan:
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sh
        args:
        - -exc
        - |
          #apk add bash > /dev/null
          apk add figlet > /dev/null
          figlet Hello World!
          figlet Some random concourse !!! ©
