resources:
- name: ingress
  type: s3
  source:
    bucket: ingress
    regexp: ingress/GH-(.*).MP4
    access_key_id: ((s3_access_id))
    secret_access_key: ((s3_access_key))
    endpoint: ((s3_host))
    disable_ssl: true
    skip_download: true
    
jobs:
- name: list_ingress
  plan:
  - get: ingress
    trigger: true
  - task: s3-list
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sh
        args:
        - -exc
        - |
          df -h
