resources:
- name: ingress_1
  type: s3
  source:
    bucket: ingress
    regexp: ingress/GH01(.*).MP4
    initial_path: ingress/GH010055.MP4
    access_key_id: ((s3_access_id))
    secret_access_key: ((s3_access_key))
    endpoint: ((s3_host))
    disable_ssl: true
    skip_download: true
    
- name: ingress_2
  type: s3
  source:
    bucket: ingress
    regexp: ingress/GH02(.*).MP4
    initial_path: ingress/GH020055.MP4
    access_key_id: ((s3_access_id))
    secret_access_key: ((s3_access_key))
    endpoint: ((s3_host))
    disable_ssl: true
    skip_download: true
    
- name: ingress_p3
  type: s3
  source:
    bucket: ingress
    regexp: ingress/GH03(.*).MP4
    initial_path: ingress/GH030055.MP4
    access_key_id: ((s3_access_id))
    secret_access_key: ((s3_access_key))
    endpoint: ((s3_host))
    disable_ssl: true
    skip_download: true
    
jobs:
- name: list_ingress
  plan:
  - get: ingress
    trigger: true
  - task: s3-list
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sh
        args:
        - -exc
        - |
          df -h
