#resources:
#- name: ingress_p1
#  type: s3
#  source:
#    bucket: ingress
#    regexp: GH01(.*).MP4
#    initial_path: GH010.MP4
#    access_key_id: ((s3_access_id))
#    secret_access_key: ((s3_access_key))
#    endpoint: ((s3_host))
#    cloudfront_url: ((s3_host))
#    disable_ssl: true

jobs:
- name: list_ingress
  plan:
  #- in_parallel:  
  #  - get: ingress_p1
 #   - get: ingress_p2
#    - get: ingress_p3
  - task: mount_ingress
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sh
        args:
        - -exc
        - |
          set +x
          apk add cifs-utils
          apk add ffmpeg
          mkdir /mnt/ingress
          mount -t cifs ((nas_adr)) /mnt/ingress -o vers=3.0,username=((nas_adm)),password=((nas_pw)),dir_mode=0777,file_mode=0777,serverino
          cd /mnt/ingress
          ls -altrh
          cd -
          echo
          echo
          echo "Get part"
          cp /mnt/ingress/GH010057.MP4 ./GH010057.MP4
          echo
          ls -altrh
          echo "Extract frame"
          ffmpeg -i ./GH010057.MP4 -s 2704x1520 -vframes 1 -f image2 frame.png
          cp ./frame.png /mnt/ingress/frame.png
          echo done
