resource_types:
- name: ssl_check
  type: docker-image
  source:
    repository: gutzel/concourse-ssl-timer-resource
    tag: latest

resources:
- name: boring_cloud_ssl
  type: ssl_check
  source:
    dns: google.com

jobs:
- name: check-ssl-days
  plan:
  - get: boring_cloud_ssl
  - task: check-cert-by-dns
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sh
        args:
        - -exc
        - |
          echo ":)"
