resource_types:
- name: ssl_check
  type: docker-image
  source:
    repository: gutzel/concourse-ssl-timer-resource
    tag: latest

resources:
- name: boring_cloud_ssl
  type: ssl_check
  source:
    dns: boring.cloud

- name: eu1_dev_ssl
  type: ssl_check
  source:
    dns: www.eu1.dev

jobs:
- name: check-ssl-days
  plan:
  - in_parallel:
    - get: boring_cloud_ssl
    - get: eu1_dev_ssl  
  - task: check-cert-by-dns
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
      - name: boring_cloud_ssl
      run:
        path: sh
        args:
        - -exc
        - |
          set +x
          echo "Days left SSL cert:"
          cat boring_cloud_ssl/info.txt
          echo
          echo "Installing git + python"          
          apk add git python3 python3-setuptools 2>&1 >/dev/null
          git clone https://github.com/certbot/certbot.git 2>&1 >/dev/null
          git clone https://github.com/oGGy990/certbot-dns-inwx.git 2>&1 >/dev/null
          cd certbot-dns-inwx
          python3 setup.py develop --no-deps
          cat /etc/letsencrypt/inwx.cfg

