resource_types:
- name: ssl_check
  type: docker-image
  source:
    repository: gutzel/concourse-ssl-timer-resource
    tag: latest

resources:
- name: boring_cloud_ssl
  type: ssl_check
  icon: certificate-outline
  source:
    dns: boring.cloud

- name: eu1_dev_ssl
  type: ssl_check
  icon: certificate-outline
  source:
    dns: www.eu1.dev

- name: certbot
  type: git
  icon: github-circle
  source:
    uri: https://github.com/certbot/certbot.git
    
- name: dns-inwx-challenge
  type: git
  icon: github-circle
  source:
    uri: https://github.com/oGGy990/certbot-dns-inwx.git

- name: my-pipelines
  type: git
  icon: wrench
  source:
    uri: https://github.com/kc1r74p/my-pipelines.git

jobs:
- name: check-ssl-days
  plan:
  - in_parallel:
    - get: boring_cloud_ssl
    - get: eu1_dev_ssl
    - get: my-pipelines
    - get: certbot
    - get: dns-inwx-challenge
  - task: check-cert-by-dns
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      inputs:
      - name: boring_cloud_ssl
      - name: certbot
      - name: dns-inwx-challenge
      - name: my-pipelines
      run:
        path: sh
        args:
        - -exc
        - |
          cd my-pipelines/scripts/          
          chmod +x certbot.sh
          ls -altr
          ./certbot.sh

